### ISSUE TITLE
[AI-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by jeonghyunje** [hackersground-kr/CloudSkillsChallenge#1]
## 챌린지 인증 내용

* 깃헙 ID: 'jeonghyunje'
* Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/69883825/
* 클라우드 스킬 챌린지 토픽/코드: 애저 AI 기초 (AI-900)

**Comment by huijun-song** [comment]
챌린지 인증 내용
깃헙 ID: thdgmlwns1
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/26856450

클라우드 스킬 챌린지 토픽/코드: 애저 AI 기초 (AI-900)
