### ISSUE TITLE
[AZ-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by tula3and** [hackersground-kr/CloudSkillsChallenge#3]
## 챌린지 인증 내용

- 깃헙 ID: `tula3and`
- Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/dayeongkang-4559/
- 클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)

**Comment by mJekal** [comment]
## 챌린지 인증 내용

깃헙 ID: `mJekal`
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/00-1935/
클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)

**Comment by thdgmlwns1** [comment]
깃헙 ID: thdgmlwns1
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/26856450/
클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)

**Comment by electrat** [comment]
* 깃헙 ID: 'electrat'
* Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/66966196/
* 클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)

**Comment by Just-Simple0** [comment]
깃헙 ID: Just-Simple0
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/justsimple-0440/
클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)

**Comment by huijun-song** [comment]
깃헙 ID: thdgmlwns1
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/26856450/
클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)
