### ISSUE TITLE
[DP-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by tula3and** [hackersground-kr/CloudSkillsChallenge#4]
## 챌린지 인증 내용

- 깃헙 ID: `tula3and`
- Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/dayeongkang-4559/
- 클라우드 스킬 챌린지 토픽/코드: 애저 데이터 기초 (DP-900)

**Comment by mJekal** [comment]
## 챌린지 인증 내용

깃헙 ID: `mJekal`
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/00-1935/
클라우드 스킬 챌린지 토픽/코드: 애저 데이터 기초 (DP-900)

**Comment by huijun-song** [comment]
깃헙 ID: thdgmlwns1
Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/26856450

클라우드 스킬 챌린지 토픽/코드: 애저 데이터 기초 (DP-900)
